name: Weekly Data Sync to Cloudflare Main

on:
  schedule:
    # æ¯é€±ä¸€æ—©ä¸Š 12 é»è§¸ç™¼ï¼ˆè‡ºç£æ™‚é–“ï¼‰
    - cron: "0 4 * * 1"

  workflow_dispatch:

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo (cf-main)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          ref: cf-main
          submodules: recursive
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Update Backend submodule
        run: |
          git submodule update --remote --merge backend

      - name: Update Frontend data
        working-directory: frontend
        run: |
          git checkout origin/cf-main -- public/

          if git diff --staged --quiet; then
            echo "No changes in frontend data."
          else
            git add .
            git commit -m "ğŸ“¦ Weekly sync data" || echo "No changes to commit"
          fi

      - name: Commit and Push changes
        run: |
          git add backend
          git add frontend
          git commit -m "ğŸ”„ Weekly sync backend and frontend data" || echo "No changes to commit"
          git push origin cf-main
